
blueprint:
  name: 'hasp-lvgl: Control Slider Object'
  description: Link a hasp-lvgl slider object with a light
  domain: automation
  
  input:
    target_entity:
      name: Entity controlled by the object
      description: Select an entity to bind with the toggle object on p<x>b<x>
      selector:
        entity:
          domain: light
    plate:
      name: hasp-lvgl Plate 
      description: Select hasp-lvgl plate whith the object
      selector:
        entity:
          integration: mqtt
          domain: binary_sensor
          device_class: moving
    page:
      name: Page ID (p<x>)
      selector: 
        number:
          min: 0
          max: 12
          mode: box
    object:
      name: Object ID (b<x>)
      selector: 
        number:
          min: 1
          max: 200
          mode: box
mode: single
max_exceeded: silent

variables:
  page: !input page
  object: !input object
  target_entity: !input target_entity
  haspentity: !input plate
  node: '{{ state_attr("" ~ haspentity ~ "","node") }}'
  state_topic: '{{ "hasp/" ~ node ~ "/state/p" ~ page ~ "b" ~ object ~ "" }}'
  command_topic: '{{ "hasp/" ~ node ~ "/command/p[" ~ page ~ "].b[" ~ object ~ "].val"}}'
trigger:
  - platform: mqtt
    topic: 'hasp/+/state/+'
  - platform: state
    entity_id: !input target_entity
  - platform: state
    entity_id: !input plate
    attribute: status
    to: available

action:
  - choose:
      - conditions:
          - condition: template
            value_template: '{{ trigger.platform == "mqtt" and trigger.topic == state_topic }}'
        sequence:
          - service: light.turn_on
            entity_id: !input target_entity
            data:
              brightness: '{{ trigger.payload_json.val | int }}'
      - conditions:
          - condition: template
            value_template: '{{ trigger.platform == "state" and trigger.entity_id == target_entity }}'
        sequence:
          - service: mqtt.publish
            data:
              topic: '{{ command_topic }}'
              payload: '{{ trigger.to_state.attributes.brightness | int }}'
      - conditions:
          - condition: template
            value_template: '{{ trigger.platform == "state" and trigger.entity_id == haspentity }}'
        sequence:
          - delay: '3' 
          - service: mqtt.publish
            data:
              topic: '{{ command_topic }}'
              payload: '{{ state_attr("" ~ target_entity ~ "", "brightness") | int }}'
